---
title: "Assignment2 - Education Equity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, error = F)

library(dplyr)
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)
library(tidycensus)

# Sys.setenv(CENSUS_KEY="e0df904ead222e4e2085d77c3a3edb8687fb35b6")

# acs_vars_2018 <- readRDS("ACS2018 metadata.rds")

census_api_key("e0df904ead222e4e2085d77c3a3edb8687fb35b6", overwrite = FALSE, install = FALSE)

acs_vars_2018 <-
  listCensusMetadata(
    name = "2018/acs/acs5/subject",
    type = "variables"
  )
saveRDS('acs_vars_2018',"ACS2018 subject metadata.rds")

```

```{r load data}
# acs_vars_2018 <- readRDS("ACS2018 subject metadata.rds")

census_race_labels <- c( 
  "White alone, not Hispanic or Latino",
  "Black alone",
  "American Indian or Alaska Native alone",
  "Asian alone",
  "Native Hawaiian and Other Pacific Islander alone)",
  "Some other race alone",
  "Two or more races")

sf_edu <-
  getCensus(
    name = "acs/acs5/subject",
    vintage = 2018,
    region = "county:075",
    regionin = "state:06",
    vars = "group(S1501)"
  ) %>%
  select(!c(state,county,NAME,GEO_ID) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2018 %>%
      select(name,label),
    by = c("variable" = "name")
  ) %>%
  separate(
    label,
    into = c(NA,"sex",NA,"race","education"),
    sep = "!!"
  ) %>%
  filter(race %in% census_race_labels) %>%
  filter(sex == "Total") %>%
  select(-sex,-variable) %>%
  pivot_wider(
    names_from = education,
    values_from = estimate
  ) %>%
  mutate(
    `High school degree` = `High school graduate or higher` - `Bachelor's degree or higher`,
    `No high school degree` = `NA` - `High school graduate or higher`,
  ) %>%
  select(race, `No high school degree`,`High school degree`,`Bachelor's degree or higher`) %>%
  bind_rows(summarise_all(., funs(if(is.numeric(.)) sum(.) else "Total"))) %>%
  pivot_longer(
    !c("race"),
    names_to = "Highest degree earned",
    values_to = "estimate"
  )

```

```{r make bar chart}

sf_edu_bar <-
  sf_edu %>%
  ggplot() +
  geom_bar(
    aes(
      x = race %>% factor(
        c(rev(census_race_labels),"Total")),
      y = estimate,
      fill = `Highest degree earned`
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "",
    y = "Fraction of population",
    title = "San Francisco education level by race",
    subtitle = "Aggregated data from 2013-2018 of education level by race for individuals over 25 years of age",
    fill = "Highest degree earned"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )

sf_edu_bar
```
```{r get puma data}
# Locate vars of interest
pums_vars_2018 <-
  pums_variables %>%
  filter(year == 2018, survey == "acs1") %>%
  distinct(var_code,var_label,data_type,level) %>%
  filter(level == "housing")

#Get IDs for PUMAs in SF
sf_county <- counties("CA",cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_pumas <-
  ca_pumas %>%
  st_centroid() %>%
  .[sf_county, ] %>%
  st_set_geometry(NULL) %>%
  left_join(ca_pumas %>% select(GEOID10)) %>%
  st_as_sf()

#Download data from these PUMAS
sf_pums <- get_pums(
  variables = c(
    "ACCESS", #internet access
    "NRC" #number of related children in household
    ),
  state = "CA",
  puma = sf_pumas$PUMACE10,
  survey = "acs1",
  rep_weights = "housing",
  year = 2018,
  recode = T
) %>%
  select(SERIALNO,NRC,ACCESS_label,WGTP) %>%
  filter(
    WGTP != 0
  )

```

```{r filter puma data}
sf_kids_with_internet <-
  sf_pums %>%
  filter(
    ACCESS_label != "No access to the Internet at this house, apartment, or mobile home"
  ) %>%
  mutate(
    total_kids = NRC*WGTP
  ) %>%
  summarize(
    total = sum(total_kids)
  )

sf_kids_without_internet <-
  sf_pums %>%
  filter(
    ACCESS_label == "No access to the Internet at this house, apartment, or mobile home"
  ) %>%
  mutate(
    total_kids = NRC*WGTP
  ) %>%
  summarize(
    total = sum(total_kids)
  )
  
sf_kids_without_internet
sf_kids_without_internet/(sf_kids_with_internet + sf_kids_without_internet)*100

```

```{r migration analysis}

library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="e0df904ead222e4e2085d77c3a3edb8687fb35b6")

acs_vars_2019_1yr <-  listCensusMetadata(
    name = "2019/acs/acs1",
    type = "variables"
  )

sf_migration_this_year_19 <-
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:075",
    regionin = "state:06",
    vars = "group(B07009)"
  ) %>%
  select(!c(state,county,GEO_ID,NAME) & !ends_with(c("MA","EA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "vars",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>%
      select(name,label),
    by = c("vars" = "name")
  ) %>%
  select(-vars) %>%
  separate(
    label,
    into = c(NA,NA,"mobility","education"),
    sep = "!!"
  ) %>%
  filter(!is.na(education)) %>%
  mutate(
    mobility = ifelse(
      mobility %in% c("Same house 1 year ago:","Moved within same county:"),
      "Here since last year",
      "Inflow"
    )
  ) %>%
  group_by(mobility,education) %>%
  summarize(
    estimate = sum(estimate)
  )

sf_migration_last_year_19 <-
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:075",
    regionin = "state:06",
    vars = "group(B07409)"
  ) %>%
  select(!c(state,county,GEO_ID,NAME) & !ends_with(c("MA","EA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "vars",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>%
      select(name,label),
    by = c("vars" = "name")
  ) %>%
  select(-vars) %>%
  separate(
    label,
    into = c(NA,NA,"mobility","education"),
    sep = "!!"
  ) %>%
  filter(!is.na(education)) %>%
  mutate(
    mobility = ifelse(
      mobility %in% c("Same house:","Moved within same county:"),
      "Here since last year",
      "Outflow"
    )
  ) %>%
  group_by(mobility,education) %>%
  summarize(
    estimate = sum(estimate)
  )

sf_migration_this_year_18 <-getCensus(
    name = "acs/acs1",
    vintage = 2018,
    region = "county:075",
    regionin = "state:06",
    vars = "group(B07009)"
  ) %>%
  select(!c(state,county,GEO_ID,NAME) & !ends_with(c("MA","EA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "vars",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>%
      select(name,label),
    by = c("vars" = "name")
  ) %>%
  select(-vars) %>%
  separate(
    label,
    into = c(NA,NA,"mobility","education"),
    sep = "!!"
  ) %>%
  filter(!is.na(education)) %>%
  mutate(
    mobility = "Here last year"
  ) %>%
  group_by(mobility,education) %>%
  summarize(estimate = sum(estimate))
  
edu_levels = c("Less than high school graduate","High school graduate (includes equivalency)","Some college or associate's degree","Bachelor's degree","Graduate or professional degree")
  
sf_flows_by_edu <-
  rbind(
    sf_migration_this_year_18,
    sf_migration_last_year_19 %>%
      filter(mobility == "Outflow"),
    sf_migration_this_year_19 %>%
      filter(mobility == "Inflow"),
    sf_migration_this_year_19 %>%
      group_by(education) %>%
      summarize(estimate = sum(estimate)) %>%
      mutate(mobility = "Here this year")
  ) %>%
  pivot_wider(
    names_from = mobility,
    values_from = estimate
  ) %>%
  mutate(
    `External Net` = Inflow - Outflow,
    `Internal Net` = `Here this year` - `Here last year`
  ) %>%
  select(
    Education = education,`Internal Net`,`External Net`,`Here last year`, 
    `Here this year`,Inflow,Outflow
  )

sf_flows_by_edu[order(match(sf_flows_by_edu$Education, edu_levels)),]

  # factor(
  #   Education, 
  #   levels = edu_levels, labels = levels)

# sf_flows_by_edu <- ordered(
#     factor(sf_flows_by_edu),
#     labels=levels)

```

