---
title: "Chapter2 - Equity analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, error = F)

library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="e0df904ead222e4e2085d77c3a3edb8687fb35b6")

acs_vars_2018_5yr = readRDS("ACS2018 metadata.rds")
```

```{r}
bay_income_white <-
  getCensus(
    name = "acs/acs5",
    vintage = 2018,
    region = "county:001,013,041,055,075,081,085,095,097",
    regionin = "state:06",
    vars = "group(B19001A)"
  ) %>%
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2018_5yr %>%
      select(name,label),
    by = c("variable"="name")
  ) %>%
  select(-variable) %>%
  separate(
    label,
    into = c(NA,NA,"income"),
    sep = "!!"
  ) %>%
  filter(!is.na(income))
  
```

```{r load all race data}

census_race_labels <- data.frame(
  code = c(LETTERS[1:7]),
  label = 
    c( 
      "White Alone",
      "Black or African American",
      "American Indian and Alaska Native Alone",
      "Asian Alone",
      "Native Hawaiian and Other Pacific Islander Alone)",
      "Some Other Race Alone",
      "Two or More Races"
      )
)

bay_income_race <-
  1:7 %>%
  map_dfr(function(x){
    getCensus(
      name = "acs/acs5",
      vintage = 2018,
      region = "county:001,013,041,055,075,081,085,095,097",
      regionin = "state:06",
      vars = paste0("group(B19001",LETTERS[x],")")
    ) %>%
    select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
      pivot_longer(
        ends_with("E"),
        names_to = "variable",
        values_to = "estimate"
      ) %>%
      left_join(
        acs_vars_2018_5yr %>% 
          select(name, label), 
        by = c("variable" = "name")
      ) %>% 
      select(-variable) %>% 
      separate(
        label,
        into = c(NA,NA,"income"),
        sep = "!!"
      ) %>% 
      filter(!is.na(income)) %>% 
      mutate(race = census_race_labels[x,2])
  })

```

```{r create bar charts}
bay_race_total <-
  bay_income_race %>%
  group_by(race) %>%
  summarize(estimate = sum(estimate)) %>%
  mutate(income = "Total")

bay_income_race %>%
  group_by(income,race) %>%
  summarize(estimate = sum(estimate)) %>%
  rbind(bay_race_total) %>%
  ggplot() + 
  geom_bar(
    aes(
      x = income %>% factor(
        levels = rev(c("Total",bay_income_race$income[1:16]))),
      y = estimate,
      fill = race
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Household income",
    y = "Number of households",
    title = "Bay Area household income by race",
    fill = "Race of householder"
  ) + 
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )
```
```{r some basic calculations}

((sum(bay_race_total$estimate[1:6])/sum(bay_race_total$estimate))*100) %>% round()

((bay_income_race %>%
    filter(income %in% bay_income_race$income[1:5]) %>%
    filter(race != "White Alone") %>%
    pull(estimate) %>%
    sum()) /
    (bay_income_race %>% 
    filter(income %in% bay_income_race$income[1:5]) %>% 
    pull(estimate) %>% 
    sum()) * 100) %>% 
  round()

((((bay_income_race %>% 
  filter(income %in% bay_income_race$income[1:5]) %>% 
  filter(race != "White Alone") %>% 
  pull(estimate) %>% 
  sum()) /
  (bay_income_race %>% 
    filter(income %in% bay_income_race$income[1:5]) %>% 
    pull(estimate) %>% 
    sum())) / (sum(bay_race_total$estimate[1:6])/sum(bay_race_total$estimate)) - 1) * 100) %>% 
  round()
```

```{r load air quality data, message = F}

library(readxl)

temp <- tempfile()
download.file("https://oehha.ca.gov/media/downloads/calenviroscreen/document/ces3results.xlsx",
              destfile = temp, 
              mode = "wb")
ces3 <- read_excel(temp, sheet = "CES 3.0 (2018 Update)")

unlink(temp)
```

```{r, include = T}
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

ca_tracts <- tracts("CA", cb = T, progress_bar = F)
ces3_bay_pm25 <-
  ces3 %>%
  filter(`California County` %in% bay_county_names) %>%
  select(`Census Tract`, PM2.5) %>%
  left_join(
    ca_tracts %>%
      transmute(GEOID = as.numeric(GEOID)),
    by = c("Census Tract" = "GEOID")
  ) %>%
  st_as_sf

pm25_pal <- colorNumeric(
  palette = "Reds",
  domain = ces3_bay_pm25$PM2.5,
)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = ces3_bay_pm25,
    fillColor = ~pm25_pal(PM2.5),
    color = "white",
    weight = 0.5,
    fillOpacity = 0.5,
    label = ~PM2.5
  )

summary(ces3_bay_pm25$PM2.5)
```
```{r get race data at tract level}
bay_race_tracts <-
  1:7 %>%
  map_dfr(function(x){
    getCensus(
      name = "acs/acs5",
      vintage = 2018,
      region = "tract:*",
      regionin = "state:06+county:001,013,041,055,075,081,085,095,097",
      vars = paste0("B19001",LETTERS[x],"_001E")
    ) %>%
      mutate(
        tract = paste0(state, county, tract) %>% as.numeric(),
        race = census_race_labels[x,2]
      ) %>% 
      select(
        tract,
        race,
        estimate = paste0("B19001",LETTERS[x],"_001E")
      )
  })

bay_pm25_race <-
  bay_race_tracts %>%
  left_join(
    ces3_bay_pm25 %>%
      st_set_geometry(NULL),
    by = c("tract" = "Census Tract")
  ) %>%
  mutate(
    PM2.5_tier = 
      case_when(
        PM2.5 < 7 ~ "4-7",
        PM2.5 < 8 ~ "7-8",
        PM2.5 < 9 ~ "8-9",
        PM2.5 < 10 ~ "9-10",
        TRUE ~ "10-11"
      )
  ) %>%
  group_by(race,PM2.5_tier) %>%
  summarize(estimate = sum(estimate, na.rm =T))
```

```{r plot PM2.5 exposure by race}

bay_pm25_race_stacked <-
  bay_pm25_race %>% 
  group_by(PM2.5_tier, race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  rbind(
    bay_pm25_race %>% 
      group_by(race) %>% 
      summarize(estimate = sum(estimate)) %>% 
      mutate(PM2.5_tier = "Total")
  ) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = PM2.5_tier %>% factor(levels = rev(c("Total","4-7","7-8","8-9","9-10","10-11"))),
      y = estimate,
      fill = race
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "PM2.5",
    y = "Number of households",
    title = "Bay Area PM2.5 exposure by race",
    subtitle = "Annual mean concentration of PM2.5 (average of quarterly means, µg/m3),\nover three years (2012 to 2014), aggregated by Census tract",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )

bay_pm25_race_stacked
```

