---
title: "1.9 Geospatial Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  include = FALSE, 
  warning = FALSE, 
  message = FALSE)
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)

ca_counties <- counties("CA",cb = T, progress_bar = F)

st_crs(ca_counties)


projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"


ca_counties_transformed <- 
  ca_counties %>%
  st_transform(projection)
```



```{r ggplot mapping}

ggplot(ca_counties) + geom_sf()

```
```{r leaflet mapping}

leaflet() %>%
  addTiles() %>%
  addPolygons(
    data = ca_counties %>%
      st_transform(4326)
  ) %>%
  
  addMarkers(
    data = ca_counties %>%
      st_centroid() %>%
      st_transform(4326)
  )

```

```{r plot bay area counties}
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  ca_counties %>%
  filter(NAME %in% bay_county_names)

ggplot(bay_counties) + geom_sf()

```

```{r bay cities}

ca_cities <- places("CA", cb = T, progress_bar = FALSE)

bay_cities <- ca_cities[bay_counties, ]

bay_cities_within <- 
  ca_cities %>%
  st_centroid() %>%
  .[bay_counties, ] %>%
  st_set_geometry(NULL) %>%
  left_join(ca_cities %>% select(GEOID)) %>%
  st_as_sf()
  
bay_cities_within2 <-
  ca_cities[which(ca_cities$GEOID %in% st_centroid(ca_cities)[bay_counties, ]$GEOID), ]
```

```{r map of bay area cities}

leaflet() %>%
  addTiles() %>%
  addPolygons(
    data = bay_counties %>%
      st_transform(4326),
    fill = F,
    weight = 2
  ) %>%
  addPolygons(
    data = bay_cities %>%
      filter(!GEOID %in% bay_cities_within$GEOID) %>%
      st_transform(4326),
    color = "red"
  ) %>%
  addPolygons(
    data = bay_cities_within %>%
      st_transform(4326),
    color = "green"
  )

```

```{r census groups}
bay_cbgs <-
  bay_county_names %>%
  map_dfr(function(county) {
    block_groups("CA", county, cb = T, progress_bar = F)
  })

bay_cbgs_clip <- st_read("https://opendata.arcgis.com/datasets/037fc1597b5a4c6994b89c46a8fb4f06_0.geojson")

ggplot(bay_cbgs_clip)+geom_sf()

```


```{r map PGE data}
usa_zips <- zctas(cb = T, progress_bar = F)

bay_zips <- usa_zips %>%
  st_centroid() %>%
  .[bay_counties, ] %>%
  st_set_geometry(NULL) %>%
  left_join(usa_zips %>% select(GEOID10)) %>%
  st_as_sf()

# load PGE data
pge_19_elec <- readRDS("pge_19_elec.rds")

pge_19_res_elec <-
  pge_19_elec %>%
  filter(CUSTOMERCLASS == "Elec- Residential") %>%
  mutate(
    ZIPCODE = ZIPCODE %>% as.character()
  ) %>%
  group_by(ZIPCODE) %>%
  summarize(
    TOTALKWH = sum(TOTALKWH, na.rm = T)
  ) %>%
  
  right_join(
    bay_zips %>% select(GEOID10),
    by = c("ZIPCODE" = "GEOID10")
  ) %>%
  st_as_sf() %>%
  st_transform(4326)

# create color palette
res_pal <- colorNumeric(
  palette = "Blues",
  domain = 
    pge_19_res_elec$TOTALKWH
)

# map it out
leaflet() %>%
  addTiles() %>%
  addPolygons(
    data = pge_19_res_elec,
    fillColor = ~res_pal(TOTALKWH),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(TOTALKWH), "kWh total in",
      ZIPCODE
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    ) 
  ) %>%
  addLegend(
    data = pge_19_res_elec,
    pal = res_pal,
    values = ~TOTALKWH,
    title = "Total Residential<br>kWh, 2019"
  )  
  
```
```{r map health data}

ca_tracts <- tracts("CA", cb = T, progress_bar = F)
health_ca <- readRDS("health_ca.rds")

bay_phys_health_17 <-
  health_ca %>%
  filter(!is.na(TractFIPS)) %>%
  filter(MeasureId == "PHLTH") %>%
  filter(!is.na(Data_Value)) %>%
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("TractFIPS" = "GEOID")
  ) %>%
  st_as_sf() %>%
  st_centroid() %>%
  .[bay_counties, ] %>%
  st_set_geometry(NULL) %>%
  left_join(
    ca_tracts %>% select(GEOID),
    by = c("TractFIPS" = "GEOID")
  ) %>%
  st_as_sf()

health_pal <- colorNumeric(
  palette = "Purples",
  domain = 
    bay_phys_health_17$Data_Value
)

leaflet() %>%
  addTiles() %>%
  addPolygons(
    data = bay_phys_health_17,
    fillColor = ~health_pal(Data_Value),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.8,
    weight = 1,
    label = ~paste0(
      round(Data_Value),
      "% in ", TractFIPS
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
    
  ) %>%
  
  addLegend(
    data = bay_phys_health_17,
    pal = health_pal,
    values = ~Data_Value,
    title = "Physical health<br>not good for 14+ days<br> among adults aged<br>18+ years, 2019"
  )
```

