---
title: "1.6 loops"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,include = FALSE, warning = FALSE, message = FALSE)
```

#blah


```{r loops}
library(tidyverse)

year <- 2019
quarters <- 1:4
type <- "Electric"

pge_19_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0("PGE_",year,
           "_Q",quarter,
           "_",type,"UsageByZip.csv")
  
  print(filename)
  
  temp <- read_csv(filename)
  
  pge_19_elec <- rbind(pge_19_elec,temp)
  
  saveRDS(pge_19_elec,"pge_19_elec.rds")
}

rm(filename,quarter,quarters,type,year)
```

## Manipulating Data

```{r manipulate}
pge_filter <- filter(pge_19_elec,CUSTOMERCLASS %in% c("Elec- Residential","Elec- Commercial"))

pge_select <- select(
  pge_filter,
  !c("YEAR", "COMBINED", "AVERAGEKWH")
)

pge_group <- group_by(
  pge_select,
  MONTH,
  CUSTOMERCLASS
)

pge_summarize <-
  summarize(
    pge_group,
    TOTALKWH = 
      sum(
        TOTALKWH,
        na.rm = T
      )
  )


pge_wide <-
  pivot_wider(
    pge_summarize,
    names_from = CUSTOMERCLASS,
    values_from = TOTALKWH
  )

pge_tidy <- 
  pivot_longer(
    pge_wide,
    c("Elec- Commercial", "Elec- Residential"),
    names_to = "CUSTOMERCLASS",
    values_to = "TOTALKWH"
  )

pge_summarize <-
  summarize(
    pge_group,
    TOTALKWH = 
      sum(
        TOTALKWH,
        na.rm = T
      ),
    TOTALCUSTOMERS = 
      sum(
        TOTALCUSTOMERS,
        na.rm = T
      )
  )

pge_mutate <-
  mutate(
    pge_summarize,
    AVERAGEKWH = 
      TOTALKWH/TOTALCUSTOMERS
  )

```


```{r pipeline technique}
pge_final <- 
  pge_19_elec %>%
  
  filter(
    CUSTOMERCLASS %in%
      c("Elec- Residential", "Elec- Commercial")
  ) %>%
  
  select(
    !c(YEAR,COMBINED,AVERAGEKWH)
  ) %>%
  
  group_by(MONTH,CUSTOMERCLASS) %>%
  
  summarize(
    TOTALKWH = 
      sum(
        TOTALKWH,
        na.rm = T
      ),
    TOTALCUSTOMERS = 
      sum(
        TOTALCUSTOMERS,
        na.rm = T
      )
  ) %>%
  
  mutate(
    AVERAGEKWH = 
      TOTALKWH/TOTALCUSTOMERS
  )
  
  # pivot_wider(    
    # names_from = CUSTOMERCLASS,
    # values_from = c(TOTALKWH,TOTALCUSTOMERS,AVERAGEKWH)
  # )

```

## ADDING PLOTS

```{r ggplotting}
library(plotly)

pge_chart <-
  pge_final %>%
  
  ggplot() + 
  geom_bar(
    aes(
      x = MONTH %>% factor(),
      y = TOTALKWH,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack" #or "dodge"
  ) + 
  labs(
    x = "Month",
    y = "kWh",
    title = "PG&E Territory Monthly Electricity Usage, 2019",
    fill = "Electricity Type"
  )


pge_chart

```


```{r convert to plotly}
pge_chart %>% ggplotly() %>%
  layout(
    xaxis = list(fixedrange = T),
    yaxis = list(fixedrange = T)
  ) %>%
  config(displayModeBar = F)
```


You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
